### ISSUE TITLE
Plugin license

### ISSUE THREAD

**Issue by siepkes** [kofemann/opendj-kpa#1]
First of all great work on this plugin! I was wondering though if you could clarify what the license of the plugin is? Is it CDDL like OpenDJ itself? Or perhaps something else?

**Comment by kofemann** [comment]
Hi,
It's licenses with CDDL. I just updated (2d6d8ca) README file to explicitly mention the license.

**Comment by siepkes** [comment]
Great! Thanks a bunch!
